# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from likho.ml.v1 import ml_pb2 as likho_dot_ml_dot_v1_dot_ml__pb2


class MlServiceStub:
    """Owned by likho-ml: which speech models exist and which one transcribes by default, how well
    each does on a workspace's gold set (calls a person has corrected with care), the training
    examples people's corrections make, and fine-tuning runs.

    A model is named by its registry id, "<engine>/<name>" (faster-whisper/turbo, or a fine-tuned
    faster-whisper/likho-2026-10); the transcription service loads models by that id.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListModels = channel.unary_unary(
                '/likho.ml.v1.MlService/ListModels',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.GetModel = channel.unary_unary(
                '/likho.ml.v1.MlService/GetModel',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetModelRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetModelResponse.FromString,
                _registered_method=True)
        self.GetDefault = channel.unary_unary(
                '/likho.ml.v1.MlService/GetDefault',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetDefaultRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetDefaultResponse.FromString,
                _registered_method=True)
        self.RegisterModel = channel.unary_unary(
                '/likho.ml.v1.MlService/RegisterModel',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.RegisterModelRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.RegisterModelResponse.FromString,
                _registered_method=True)
        self.SetDefault = channel.unary_unary(
                '/likho.ml.v1.MlService/SetDefault',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.SetDefaultRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.SetDefaultResponse.FromString,
                _registered_method=True)
        self.RetireModel = channel.unary_unary(
                '/likho.ml.v1.MlService/RetireModel',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.RetireModelRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.RetireModelResponse.FromString,
                _registered_method=True)
        self.AddToGoldSet = channel.unary_unary(
                '/likho.ml.v1.MlService/AddToGoldSet',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.AddToGoldSetRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.AddToGoldSetResponse.FromString,
                _registered_method=True)
        self.RemoveFromGoldSet = channel.unary_unary(
                '/likho.ml.v1.MlService/RemoveFromGoldSet',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.RemoveFromGoldSetRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.RemoveFromGoldSetResponse.FromString,
                _registered_method=True)
        self.ListGoldSet = channel.unary_unary(
                '/likho.ml.v1.MlService/ListGoldSet',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListGoldSetRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListGoldSetResponse.FromString,
                _registered_method=True)
        self.StartEvaluation = channel.unary_unary(
                '/likho.ml.v1.MlService/StartEvaluation',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.StartEvaluationRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.StartEvaluationResponse.FromString,
                _registered_method=True)
        self.GetEvaluation = channel.unary_unary(
                '/likho.ml.v1.MlService/GetEvaluation',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetEvaluationRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetEvaluationResponse.FromString,
                _registered_method=True)
        self.ListEvaluations = channel.unary_unary(
                '/likho.ml.v1.MlService/ListEvaluations',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListEvaluationsRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListEvaluationsResponse.FromString,
                _registered_method=True)
        self.GetTrainingStats = channel.unary_unary(
                '/likho.ml.v1.MlService/GetTrainingStats',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetTrainingStatsRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetTrainingStatsResponse.FromString,
                _registered_method=True)
        self.ExportDataset = channel.unary_unary(
                '/likho.ml.v1.MlService/ExportDataset',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ExportDatasetRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ExportDatasetResponse.FromString,
                _registered_method=True)
        self.StartTrainingRun = channel.unary_unary(
                '/likho.ml.v1.MlService/StartTrainingRun',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.StartTrainingRunRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.StartTrainingRunResponse.FromString,
                _registered_method=True)
        self.ListTrainingRuns = channel.unary_unary(
                '/likho.ml.v1.MlService/ListTrainingRuns',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListTrainingRunsRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListTrainingRunsResponse.FromString,
                _registered_method=True)
        self.ReportTrainingRun = channel.unary_unary(
                '/likho.ml.v1.MlService/ReportTrainingRun',
                request_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ReportTrainingRunRequest.SerializeToString,
                response_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ReportTrainingRunResponse.FromString,
                _registered_method=True)


class MlServiceServicer:
    """Owned by likho-ml: which speech models exist and which one transcribes by default, how well
    each does on a workspace's gold set (calls a person has corrected with care), the training
    examples people's corrections make, and fine-tuning runs.

    A model is named by its registry id, "<engine>/<name>" (faster-whisper/turbo, or a fine-tuned
    faster-whisper/likho-2026-10); the transcription service loads models by that id.
    """

    def ListModels(self, request, context):
        """The registered models, the default first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefault(self, request, context):
        """The model new transcriptions use. Never empty once likho-ml has started.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterModel(self, request, context):
        """Adds a model (a fine-tuned one, or another size of an engine). Its registry id must be new.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefault(self, request, context):
        """Makes a model the default; publishes likho.model.chosen.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetireModel(self, request, context):
        """A retired model is kept (its evaluations and transcripts name it) but cannot be the default.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddToGoldSet(self, request, context):
        """The gold set: recordings whose latest transcript a person has checked line by line. The
        reference text of an evaluation is that transcript as it was when the recording was added.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveFromGoldSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGoldSet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartEvaluation(self, request, context):
        """Transcribes every recording of the gold set with a model and scores it against the
        references. Answers at once (status queued); likho.evaluation.completed follows.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvaluation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEvaluations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrainingStats(self, request, context):
        """What people's corrections have given so far: lines, audio, by layer.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportDataset(self, request, context):
        """Writes the training examples (audio spans and corrected text) to the models bucket as a
        dataset a fine-tuning job reads.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTrainingRun(self, request, context):
        """Records a fine-tuning run of a dataset on a base model and hands it to the configured
        launcher (a GPU machine or a cloud job); without one the run waits as "pending".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTrainingRuns(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTrainingRun(self, request, context):
        """What the fine-tuning job tells about its run: running, failed, or completed with the
        weights it wrote - which registers the new model (fine-tuned from the run's base model).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListModelsRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListModelsResponse.SerializeToString,
            ),
            'GetModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetModelRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetModelResponse.SerializeToString,
            ),
            'GetDefault': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefault,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetDefaultRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetDefaultResponse.SerializeToString,
            ),
            'RegisterModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterModel,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.RegisterModelRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.RegisterModelResponse.SerializeToString,
            ),
            'SetDefault': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefault,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.SetDefaultRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.SetDefaultResponse.SerializeToString,
            ),
            'RetireModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RetireModel,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.RetireModelRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.RetireModelResponse.SerializeToString,
            ),
            'AddToGoldSet': grpc.unary_unary_rpc_method_handler(
                    servicer.AddToGoldSet,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.AddToGoldSetRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.AddToGoldSetResponse.SerializeToString,
            ),
            'RemoveFromGoldSet': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveFromGoldSet,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.RemoveFromGoldSetRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.RemoveFromGoldSetResponse.SerializeToString,
            ),
            'ListGoldSet': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGoldSet,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListGoldSetRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListGoldSetResponse.SerializeToString,
            ),
            'StartEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.StartEvaluation,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.StartEvaluationRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.StartEvaluationResponse.SerializeToString,
            ),
            'GetEvaluation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvaluation,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetEvaluationRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetEvaluationResponse.SerializeToString,
            ),
            'ListEvaluations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEvaluations,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListEvaluationsRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListEvaluationsResponse.SerializeToString,
            ),
            'GetTrainingStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingStats,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetTrainingStatsRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.GetTrainingStatsResponse.SerializeToString,
            ),
            'ExportDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportDataset,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ExportDatasetRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ExportDatasetResponse.SerializeToString,
            ),
            'StartTrainingRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrainingRun,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.StartTrainingRunRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.StartTrainingRunResponse.SerializeToString,
            ),
            'ListTrainingRuns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTrainingRuns,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListTrainingRunsRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ListTrainingRunsResponse.SerializeToString,
            ),
            'ReportTrainingRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTrainingRun,
                    request_deserializer=likho_dot_ml_dot_v1_dot_ml__pb2.ReportTrainingRunRequest.FromString,
                    response_serializer=likho_dot_ml_dot_v1_dot_ml__pb2.ReportTrainingRunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likho.ml.v1.MlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likho.ml.v1.MlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MlService:
    """Owned by likho-ml: which speech models exist and which one transcribes by default, how well
    each does on a workspace's gold set (calls a person has corrected with care), the training
    examples people's corrections make, and fine-tuning runs.

    A model is named by its registry id, "<engine>/<name>" (faster-whisper/turbo, or a fine-tuned
    faster-whisper/likho-2026-10); the transcription service loads models by that id.
    """

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/ListModels',
            likho_dot_ml_dot_v1_dot_ml__pb2.ListModelsRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/GetModel',
            likho_dot_ml_dot_v1_dot_ml__pb2.GetModelRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.GetModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDefault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/GetDefault',
            likho_dot_ml_dot_v1_dot_ml__pb2.GetDefaultRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.GetDefaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/RegisterModel',
            likho_dot_ml_dot_v1_dot_ml__pb2.RegisterModelRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.RegisterModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDefault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/SetDefault',
            likho_dot_ml_dot_v1_dot_ml__pb2.SetDefaultRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.SetDefaultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetireModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/RetireModel',
            likho_dot_ml_dot_v1_dot_ml__pb2.RetireModelRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.RetireModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddToGoldSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/AddToGoldSet',
            likho_dot_ml_dot_v1_dot_ml__pb2.AddToGoldSetRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.AddToGoldSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveFromGoldSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/RemoveFromGoldSet',
            likho_dot_ml_dot_v1_dot_ml__pb2.RemoveFromGoldSetRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.RemoveFromGoldSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGoldSet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/ListGoldSet',
            likho_dot_ml_dot_v1_dot_ml__pb2.ListGoldSetRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.ListGoldSetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/StartEvaluation',
            likho_dot_ml_dot_v1_dot_ml__pb2.StartEvaluationRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.StartEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvaluation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/GetEvaluation',
            likho_dot_ml_dot_v1_dot_ml__pb2.GetEvaluationRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.GetEvaluationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEvaluations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/ListEvaluations',
            likho_dot_ml_dot_v1_dot_ml__pb2.ListEvaluationsRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.ListEvaluationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrainingStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/GetTrainingStats',
            likho_dot_ml_dot_v1_dot_ml__pb2.GetTrainingStatsRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.GetTrainingStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/ExportDataset',
            likho_dot_ml_dot_v1_dot_ml__pb2.ExportDatasetRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.ExportDatasetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTrainingRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/StartTrainingRun',
            likho_dot_ml_dot_v1_dot_ml__pb2.StartTrainingRunRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.StartTrainingRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTrainingRuns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/ListTrainingRuns',
            likho_dot_ml_dot_v1_dot_ml__pb2.ListTrainingRunsRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.ListTrainingRunsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportTrainingRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.ml.v1.MlService/ReportTrainingRun',
            likho_dot_ml_dot_v1_dot_ml__pb2.ReportTrainingRunRequest.SerializeToString,
            likho_dot_ml_dot_v1_dot_ml__pb2.ReportTrainingRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
