# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from likho.language.v1 import language_pb2 as likho_dot_language_dot_v1_dot_language__pb2


class LanguageServiceStub:
    """Owned by likho-language: Hinglish rules, the spelling table, the glossary and the language policy.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transliterate = channel.unary_unary(
                '/likho.language.v1.LanguageService/Transliterate',
                request_serializer=likho_dot_language_dot_v1_dot_language__pb2.TransliterateRequest.SerializeToString,
                response_deserializer=likho_dot_language_dot_v1_dot_language__pb2.TransliterateResponse.FromString,
                _registered_method=True)
        self.TransliterateBatch = channel.unary_unary(
                '/likho.language.v1.LanguageService/TransliterateBatch',
                request_serializer=likho_dot_language_dot_v1_dot_language__pb2.TransliterateBatchRequest.SerializeToString,
                response_deserializer=likho_dot_language_dot_v1_dot_language__pb2.TransliterateBatchResponse.FromString,
                _registered_method=True)
        self.GetHotwords = channel.unary_unary(
                '/likho.language.v1.LanguageService/GetHotwords',
                request_serializer=likho_dot_language_dot_v1_dot_language__pb2.GetHotwordsRequest.SerializeToString,
                response_deserializer=likho_dot_language_dot_v1_dot_language__pb2.GetHotwordsResponse.FromString,
                _registered_method=True)
        self.ResolveDecodePolicy = channel.unary_unary(
                '/likho.language.v1.LanguageService/ResolveDecodePolicy',
                request_serializer=likho_dot_language_dot_v1_dot_language__pb2.ResolveDecodePolicyRequest.SerializeToString,
                response_deserializer=likho_dot_language_dot_v1_dot_language__pb2.ResolveDecodePolicyResponse.FromString,
                _registered_method=True)
        self.ListGlossaryTerms = channel.unary_unary(
                '/likho.language.v1.LanguageService/ListGlossaryTerms',
                request_serializer=likho_dot_language_dot_v1_dot_language__pb2.ListGlossaryTermsRequest.SerializeToString,
                response_deserializer=likho_dot_language_dot_v1_dot_language__pb2.ListGlossaryTermsResponse.FromString,
                _registered_method=True)
        self.UpsertGlossaryTerm = channel.unary_unary(
                '/likho.language.v1.LanguageService/UpsertGlossaryTerm',
                request_serializer=likho_dot_language_dot_v1_dot_language__pb2.UpsertGlossaryTermRequest.SerializeToString,
                response_deserializer=likho_dot_language_dot_v1_dot_language__pb2.UpsertGlossaryTermResponse.FromString,
                _registered_method=True)
        self.DeleteGlossaryTerm = channel.unary_unary(
                '/likho.language.v1.LanguageService/DeleteGlossaryTerm',
                request_serializer=likho_dot_language_dot_v1_dot_language__pb2.DeleteGlossaryTermRequest.SerializeToString,
                response_deserializer=likho_dot_language_dot_v1_dot_language__pb2.DeleteGlossaryTermResponse.FromString,
                _registered_method=True)
        self.ListSpellings = channel.unary_unary(
                '/likho.language.v1.LanguageService/ListSpellings',
                request_serializer=likho_dot_language_dot_v1_dot_language__pb2.ListSpellingsRequest.SerializeToString,
                response_deserializer=likho_dot_language_dot_v1_dot_language__pb2.ListSpellingsResponse.FromString,
                _registered_method=True)
        self.UpsertSpelling = channel.unary_unary(
                '/likho.language.v1.LanguageService/UpsertSpelling',
                request_serializer=likho_dot_language_dot_v1_dot_language__pb2.UpsertSpellingRequest.SerializeToString,
                response_deserializer=likho_dot_language_dot_v1_dot_language__pb2.UpsertSpellingResponse.FromString,
                _registered_method=True)
        self.DeleteSpelling = channel.unary_unary(
                '/likho.language.v1.LanguageService/DeleteSpelling',
                request_serializer=likho_dot_language_dot_v1_dot_language__pb2.DeleteSpellingRequest.SerializeToString,
                response_deserializer=likho_dot_language_dot_v1_dot_language__pb2.DeleteSpellingResponse.FromString,
                _registered_method=True)


class LanguageServiceServicer:
    """Owned by likho-language: Hinglish rules, the spelling table, the glossary and the language policy.
    """

    def Transliterate(self, request, context):
        """Writes one line in Hinglish using the rules and the workspace's spelling table.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransliterateBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHotwords(self, request, context):
        """Names the speech model should listen for.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveDecodePolicy(self, request, context):
        """Decides which language to decode as, from what was detected.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGlossaryTerms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertGlossaryTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGlossaryTerm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSpellings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertSpelling(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSpelling(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanguageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transliterate': grpc.unary_unary_rpc_method_handler(
                    servicer.Transliterate,
                    request_deserializer=likho_dot_language_dot_v1_dot_language__pb2.TransliterateRequest.FromString,
                    response_serializer=likho_dot_language_dot_v1_dot_language__pb2.TransliterateResponse.SerializeToString,
            ),
            'TransliterateBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.TransliterateBatch,
                    request_deserializer=likho_dot_language_dot_v1_dot_language__pb2.TransliterateBatchRequest.FromString,
                    response_serializer=likho_dot_language_dot_v1_dot_language__pb2.TransliterateBatchResponse.SerializeToString,
            ),
            'GetHotwords': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHotwords,
                    request_deserializer=likho_dot_language_dot_v1_dot_language__pb2.GetHotwordsRequest.FromString,
                    response_serializer=likho_dot_language_dot_v1_dot_language__pb2.GetHotwordsResponse.SerializeToString,
            ),
            'ResolveDecodePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveDecodePolicy,
                    request_deserializer=likho_dot_language_dot_v1_dot_language__pb2.ResolveDecodePolicyRequest.FromString,
                    response_serializer=likho_dot_language_dot_v1_dot_language__pb2.ResolveDecodePolicyResponse.SerializeToString,
            ),
            'ListGlossaryTerms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGlossaryTerms,
                    request_deserializer=likho_dot_language_dot_v1_dot_language__pb2.ListGlossaryTermsRequest.FromString,
                    response_serializer=likho_dot_language_dot_v1_dot_language__pb2.ListGlossaryTermsResponse.SerializeToString,
            ),
            'UpsertGlossaryTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertGlossaryTerm,
                    request_deserializer=likho_dot_language_dot_v1_dot_language__pb2.UpsertGlossaryTermRequest.FromString,
                    response_serializer=likho_dot_language_dot_v1_dot_language__pb2.UpsertGlossaryTermResponse.SerializeToString,
            ),
            'DeleteGlossaryTerm': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGlossaryTerm,
                    request_deserializer=likho_dot_language_dot_v1_dot_language__pb2.DeleteGlossaryTermRequest.FromString,
                    response_serializer=likho_dot_language_dot_v1_dot_language__pb2.DeleteGlossaryTermResponse.SerializeToString,
            ),
            'ListSpellings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSpellings,
                    request_deserializer=likho_dot_language_dot_v1_dot_language__pb2.ListSpellingsRequest.FromString,
                    response_serializer=likho_dot_language_dot_v1_dot_language__pb2.ListSpellingsResponse.SerializeToString,
            ),
            'UpsertSpelling': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertSpelling,
                    request_deserializer=likho_dot_language_dot_v1_dot_language__pb2.UpsertSpellingRequest.FromString,
                    response_serializer=likho_dot_language_dot_v1_dot_language__pb2.UpsertSpellingResponse.SerializeToString,
            ),
            'DeleteSpelling': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSpelling,
                    request_deserializer=likho_dot_language_dot_v1_dot_language__pb2.DeleteSpellingRequest.FromString,
                    response_serializer=likho_dot_language_dot_v1_dot_language__pb2.DeleteSpellingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likho.language.v1.LanguageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likho.language.v1.LanguageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LanguageService:
    """Owned by likho-language: Hinglish rules, the spelling table, the glossary and the language policy.
    """

    @staticmethod
    def Transliterate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.language.v1.LanguageService/Transliterate',
            likho_dot_language_dot_v1_dot_language__pb2.TransliterateRequest.SerializeToString,
            likho_dot_language_dot_v1_dot_language__pb2.TransliterateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransliterateBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.language.v1.LanguageService/TransliterateBatch',
            likho_dot_language_dot_v1_dot_language__pb2.TransliterateBatchRequest.SerializeToString,
            likho_dot_language_dot_v1_dot_language__pb2.TransliterateBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHotwords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.language.v1.LanguageService/GetHotwords',
            likho_dot_language_dot_v1_dot_language__pb2.GetHotwordsRequest.SerializeToString,
            likho_dot_language_dot_v1_dot_language__pb2.GetHotwordsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveDecodePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.language.v1.LanguageService/ResolveDecodePolicy',
            likho_dot_language_dot_v1_dot_language__pb2.ResolveDecodePolicyRequest.SerializeToString,
            likho_dot_language_dot_v1_dot_language__pb2.ResolveDecodePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGlossaryTerms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.language.v1.LanguageService/ListGlossaryTerms',
            likho_dot_language_dot_v1_dot_language__pb2.ListGlossaryTermsRequest.SerializeToString,
            likho_dot_language_dot_v1_dot_language__pb2.ListGlossaryTermsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertGlossaryTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.language.v1.LanguageService/UpsertGlossaryTerm',
            likho_dot_language_dot_v1_dot_language__pb2.UpsertGlossaryTermRequest.SerializeToString,
            likho_dot_language_dot_v1_dot_language__pb2.UpsertGlossaryTermResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGlossaryTerm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.language.v1.LanguageService/DeleteGlossaryTerm',
            likho_dot_language_dot_v1_dot_language__pb2.DeleteGlossaryTermRequest.SerializeToString,
            likho_dot_language_dot_v1_dot_language__pb2.DeleteGlossaryTermResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSpellings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.language.v1.LanguageService/ListSpellings',
            likho_dot_language_dot_v1_dot_language__pb2.ListSpellingsRequest.SerializeToString,
            likho_dot_language_dot_v1_dot_language__pb2.ListSpellingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertSpelling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.language.v1.LanguageService/UpsertSpelling',
            likho_dot_language_dot_v1_dot_language__pb2.UpsertSpellingRequest.SerializeToString,
            likho_dot_language_dot_v1_dot_language__pb2.UpsertSpellingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSpelling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.language.v1.LanguageService/DeleteSpelling',
            likho_dot_language_dot_v1_dot_language__pb2.DeleteSpellingRequest.SerializeToString,
            likho_dot_language_dot_v1_dot_language__pb2.DeleteSpellingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
