# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from likho.media.v1 import media_pb2 as likho_dot_media_dot_v1_dot_media__pb2


class MediaServiceStub:
    """Owned by likho-media: uploads, duplicate check, waveform, a playable copy where needed, download links.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMedia = channel.unary_unary(
                '/likho.media.v1.MediaService/GetMedia',
                request_serializer=likho_dot_media_dot_v1_dot_media__pb2.GetMediaRequest.SerializeToString,
                response_deserializer=likho_dot_media_dot_v1_dot_media__pb2.GetMediaResponse.FromString,
                _registered_method=True)
        self.CreateUpload = channel.unary_unary(
                '/likho.media.v1.MediaService/CreateUpload',
                request_serializer=likho_dot_media_dot_v1_dot_media__pb2.CreateUploadRequest.SerializeToString,
                response_deserializer=likho_dot_media_dot_v1_dot_media__pb2.CreateUploadResponse.FromString,
                _registered_method=True)
        self.GetDownloadUrl = channel.unary_unary(
                '/likho.media.v1.MediaService/GetDownloadUrl',
                request_serializer=likho_dot_media_dot_v1_dot_media__pb2.GetDownloadUrlRequest.SerializeToString,
                response_deserializer=likho_dot_media_dot_v1_dot_media__pb2.GetDownloadUrlResponse.FromString,
                _registered_method=True)
        self.DeleteMedia = channel.unary_unary(
                '/likho.media.v1.MediaService/DeleteMedia',
                request_serializer=likho_dot_media_dot_v1_dot_media__pb2.DeleteMediaRequest.SerializeToString,
                response_deserializer=likho_dot_media_dot_v1_dot_media__pb2.DeleteMediaResponse.FromString,
                _registered_method=True)


class MediaServiceServicer:
    """Owned by likho-media: uploads, duplicate check, waveform, a playable copy where needed, download links.
    """

    def GetMedia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUpload(self, request, context):
        """Returns a link the browser (or a connector) uploads the file to.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDownloadUrl(self, request, context):
        """Returns a short-lived link for playback or for a worker to download.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMedia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMedia': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMedia,
                    request_deserializer=likho_dot_media_dot_v1_dot_media__pb2.GetMediaRequest.FromString,
                    response_serializer=likho_dot_media_dot_v1_dot_media__pb2.GetMediaResponse.SerializeToString,
            ),
            'CreateUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUpload,
                    request_deserializer=likho_dot_media_dot_v1_dot_media__pb2.CreateUploadRequest.FromString,
                    response_serializer=likho_dot_media_dot_v1_dot_media__pb2.CreateUploadResponse.SerializeToString,
            ),
            'GetDownloadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDownloadUrl,
                    request_deserializer=likho_dot_media_dot_v1_dot_media__pb2.GetDownloadUrlRequest.FromString,
                    response_serializer=likho_dot_media_dot_v1_dot_media__pb2.GetDownloadUrlResponse.SerializeToString,
            ),
            'DeleteMedia': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMedia,
                    request_deserializer=likho_dot_media_dot_v1_dot_media__pb2.DeleteMediaRequest.FromString,
                    response_serializer=likho_dot_media_dot_v1_dot_media__pb2.DeleteMediaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likho.media.v1.MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likho.media.v1.MediaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaService:
    """Owned by likho-media: uploads, duplicate check, waveform, a playable copy where needed, download links.
    """

    @staticmethod
    def GetMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.media.v1.MediaService/GetMedia',
            likho_dot_media_dot_v1_dot_media__pb2.GetMediaRequest.SerializeToString,
            likho_dot_media_dot_v1_dot_media__pb2.GetMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.media.v1.MediaService/CreateUpload',
            likho_dot_media_dot_v1_dot_media__pb2.CreateUploadRequest.SerializeToString,
            likho_dot_media_dot_v1_dot_media__pb2.CreateUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDownloadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.media.v1.MediaService/GetDownloadUrl',
            likho_dot_media_dot_v1_dot_media__pb2.GetDownloadUrlRequest.SerializeToString,
            likho_dot_media_dot_v1_dot_media__pb2.GetDownloadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.media.v1.MediaService/DeleteMedia',
            likho_dot_media_dot_v1_dot_media__pb2.DeleteMediaRequest.SerializeToString,
            likho_dot_media_dot_v1_dot_media__pb2.DeleteMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
