# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from likho.search.v1 import search_pb2 as likho_dot_search_dot_v1_dot_search__pb2


class SearchServiceStub:
    """Owned by likho-search: every line of every transcript, searchable with typo tolerance
    (Hinglish is spelled many ways). It indexes transcripts as they are completed and corrected.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Search = channel.unary_unary(
                '/likho.search.v1.SearchService/Search',
                request_serializer=likho_dot_search_dot_v1_dot_search__pb2.SearchRequest.SerializeToString,
                response_deserializer=likho_dot_search_dot_v1_dot_search__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Reindex = channel.unary_unary(
                '/likho.search.v1.SearchService/Reindex',
                request_serializer=likho_dot_search_dot_v1_dot_search__pb2.ReindexRequest.SerializeToString,
                response_deserializer=likho_dot_search_dot_v1_dot_search__pb2.ReindexResponse.FromString,
                _registered_method=True)
        self.DeleteRecording = channel.unary_unary(
                '/likho.search.v1.SearchService/DeleteRecording',
                request_serializer=likho_dot_search_dot_v1_dot_search__pb2.DeleteRecordingRequest.SerializeToString,
                response_deserializer=likho_dot_search_dot_v1_dot_search__pb2.DeleteRecordingResponse.FromString,
                _registered_method=True)


class SearchServiceServicer:
    """Owned by likho-search: every line of every transcript, searchable with typo tolerance
    (Hinglish is spelled many ways). It indexes transcripts as they are completed and corrected.
    """

    def Search(self, request, context):
        """Lines matching the query in one workspace, best first, with the matches marked.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reindex(self, request, context):
        """Indexes one transcript again (or for the first time), replacing what the index holds.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRecording(self, request, context):
        """Forgets every line of a recording.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=likho_dot_search_dot_v1_dot_search__pb2.SearchRequest.FromString,
                    response_serializer=likho_dot_search_dot_v1_dot_search__pb2.SearchResponse.SerializeToString,
            ),
            'Reindex': grpc.unary_unary_rpc_method_handler(
                    servicer.Reindex,
                    request_deserializer=likho_dot_search_dot_v1_dot_search__pb2.ReindexRequest.FromString,
                    response_serializer=likho_dot_search_dot_v1_dot_search__pb2.ReindexResponse.SerializeToString,
            ),
            'DeleteRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRecording,
                    request_deserializer=likho_dot_search_dot_v1_dot_search__pb2.DeleteRecordingRequest.FromString,
                    response_serializer=likho_dot_search_dot_v1_dot_search__pb2.DeleteRecordingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likho.search.v1.SearchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likho.search.v1.SearchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SearchService:
    """Owned by likho-search: every line of every transcript, searchable with typo tolerance
    (Hinglish is spelled many ways). It indexes transcripts as they are completed and corrected.
    """

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.search.v1.SearchService/Search',
            likho_dot_search_dot_v1_dot_search__pb2.SearchRequest.SerializeToString,
            likho_dot_search_dot_v1_dot_search__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reindex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.search.v1.SearchService/Reindex',
            likho_dot_search_dot_v1_dot_search__pb2.ReindexRequest.SerializeToString,
            likho_dot_search_dot_v1_dot_search__pb2.ReindexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.search.v1.SearchService/DeleteRecording',
            likho_dot_search_dot_v1_dot_search__pb2.DeleteRecordingRequest.SerializeToString,
            likho_dot_search_dot_v1_dot_search__pb2.DeleteRecordingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
