# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from likho.dialer.v1 import dialer_pb2 as likho_dot_dialer_dot_v1_dot_dialer__pb2


class DialerServiceStub:
    """Owned by the dialer connector (likho-connector-ameyo): what the dialer knows about its
    calls, read from its reporting database - the campaigns, the agents and the calls of a
    window - so that people choose from the real lists and fetch the calls they want, and what
    the connector itself is doing (its schedule, its budget). The SQL that names the company's
    tables stays in the connector's installation; this service only fixes the shape.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCampaigns = channel.unary_unary(
                '/likho.dialer.v1.DialerService/ListCampaigns',
                request_serializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCampaignsRequest.SerializeToString,
                response_deserializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCampaignsResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/likho.dialer.v1.DialerService/ListAgents',
                request_serializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.ListCalls = channel.unary_unary(
                '/likho.dialer.v1.DialerService/ListCalls',
                request_serializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCallsRequest.SerializeToString,
                response_deserializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCallsResponse.FromString,
                _registered_method=True)
        self.GetCall = channel.unary_unary(
                '/likho.dialer.v1.DialerService/GetCall',
                request_serializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.GetCallRequest.SerializeToString,
                response_deserializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.GetCallResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/likho.dialer.v1.DialerService/GetStatus',
                request_serializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.GetStatusResponse.FromString,
                _registered_method=True)


class DialerServiceServicer:
    """Owned by the dialer connector (likho-connector-ameyo): what the dialer knows about its
    calls, read from its reporting database - the campaigns, the agents and the calls of a
    window - so that people choose from the real lists and fetch the calls they want, and what
    the connector itself is doing (its schedule, its budget). The SQL that names the company's
    tables stays in the connector's installation; this service only fixes the shape.
    """

    def ListCampaigns(self, request, context):
        """The campaigns that had calls in the window, with their counts, most calls first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """The agents that took calls in the window (of one campaign when given), most calls first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCalls(self, request, context):
        """The calls of the window, newest first, a page at a time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCall(self, request, context):
        """One call by the dialer's id of the interaction.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """What the connector is doing: the schedule, the budget, the cursor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DialerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCampaigns': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCampaigns,
                    request_deserializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCampaignsRequest.FromString,
                    response_serializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCampaignsResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListAgentsRequest.FromString,
                    response_serializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListAgentsResponse.SerializeToString,
            ),
            'ListCalls': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCalls,
                    request_deserializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCallsRequest.FromString,
                    response_serializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCallsResponse.SerializeToString,
            ),
            'GetCall': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCall,
                    request_deserializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.GetCallRequest.FromString,
                    response_serializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.GetCallResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.GetStatusRequest.FromString,
                    response_serializer=likho_dot_dialer_dot_v1_dot_dialer__pb2.GetStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likho.dialer.v1.DialerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likho.dialer.v1.DialerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DialerService:
    """Owned by the dialer connector (likho-connector-ameyo): what the dialer knows about its
    calls, read from its reporting database - the campaigns, the agents and the calls of a
    window - so that people choose from the real lists and fetch the calls they want, and what
    the connector itself is doing (its schedule, its budget). The SQL that names the company's
    tables stays in the connector's installation; this service only fixes the shape.
    """

    @staticmethod
    def ListCampaigns(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.dialer.v1.DialerService/ListCampaigns',
            likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCampaignsRequest.SerializeToString,
            likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCampaignsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.dialer.v1.DialerService/ListAgents',
            likho_dot_dialer_dot_v1_dot_dialer__pb2.ListAgentsRequest.SerializeToString,
            likho_dot_dialer_dot_v1_dot_dialer__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCalls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.dialer.v1.DialerService/ListCalls',
            likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCallsRequest.SerializeToString,
            likho_dot_dialer_dot_v1_dot_dialer__pb2.ListCallsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.dialer.v1.DialerService/GetCall',
            likho_dot_dialer_dot_v1_dot_dialer__pb2.GetCallRequest.SerializeToString,
            likho_dot_dialer_dot_v1_dot_dialer__pb2.GetCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.dialer.v1.DialerService/GetStatus',
            likho_dot_dialer_dot_v1_dot_dialer__pb2.GetStatusRequest.SerializeToString,
            likho_dot_dialer_dot_v1_dot_dialer__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
