# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from likho.insights.v1 import insights_pb2 as likho_dot_insights_dot_v1_dot_insights__pb2


class InsightsServiceStub:
    """Owned by likho-insights: what a language model says about a transcribed call - a summary, the
    products mentioned, the customer's mood, and the auditor's checks pre-filled. It works on
    transcripts as they are completed and keeps one result per transcript.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInsights = channel.unary_unary(
                '/likho.insights.v1.InsightsService/GetInsights',
                request_serializer=likho_dot_insights_dot_v1_dot_insights__pb2.GetInsightsRequest.SerializeToString,
                response_deserializer=likho_dot_insights_dot_v1_dot_insights__pb2.GetInsightsResponse.FromString,
                _registered_method=True)
        self.Analyse = channel.unary_unary(
                '/likho.insights.v1.InsightsService/Analyse',
                request_serializer=likho_dot_insights_dot_v1_dot_insights__pb2.AnalyseRequest.SerializeToString,
                response_deserializer=likho_dot_insights_dot_v1_dot_insights__pb2.AnalyseResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/likho.insights.v1.InsightsService/GetStatus',
                request_serializer=likho_dot_insights_dot_v1_dot_insights__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=likho_dot_insights_dot_v1_dot_insights__pb2.GetStatusResponse.FromString,
                _registered_method=True)


class InsightsServiceServicer:
    """Owned by likho-insights: what a language model says about a transcribed call - a summary, the
    products mentioned, the customer's mood, and the auditor's checks pre-filled. It works on
    transcripts as they are completed and keeps one result per transcript.
    """

    def GetInsights(self, request, context):
        """The insights of a recording's latest transcript (or of one transcript), if they exist.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Analyse(self, request, context):
        """Analyses a transcript now (again, when force), and answers when done.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Which model answers, and whether text may leave at all.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InsightsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInsights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInsights,
                    request_deserializer=likho_dot_insights_dot_v1_dot_insights__pb2.GetInsightsRequest.FromString,
                    response_serializer=likho_dot_insights_dot_v1_dot_insights__pb2.GetInsightsResponse.SerializeToString,
            ),
            'Analyse': grpc.unary_unary_rpc_method_handler(
                    servicer.Analyse,
                    request_deserializer=likho_dot_insights_dot_v1_dot_insights__pb2.AnalyseRequest.FromString,
                    response_serializer=likho_dot_insights_dot_v1_dot_insights__pb2.AnalyseResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=likho_dot_insights_dot_v1_dot_insights__pb2.GetStatusRequest.FromString,
                    response_serializer=likho_dot_insights_dot_v1_dot_insights__pb2.GetStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likho.insights.v1.InsightsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likho.insights.v1.InsightsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InsightsService:
    """Owned by likho-insights: what a language model says about a transcribed call - a summary, the
    products mentioned, the customer's mood, and the auditor's checks pre-filled. It works on
    transcripts as they are completed and keeps one result per transcript.
    """

    @staticmethod
    def GetInsights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.insights.v1.InsightsService/GetInsights',
            likho_dot_insights_dot_v1_dot_insights__pb2.GetInsightsRequest.SerializeToString,
            likho_dot_insights_dot_v1_dot_insights__pb2.GetInsightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Analyse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.insights.v1.InsightsService/Analyse',
            likho_dot_insights_dot_v1_dot_insights__pb2.AnalyseRequest.SerializeToString,
            likho_dot_insights_dot_v1_dot_insights__pb2.AnalyseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.insights.v1.InsightsService/GetStatus',
            likho_dot_insights_dot_v1_dot_insights__pb2.GetStatusRequest.SerializeToString,
            likho_dot_insights_dot_v1_dot_insights__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
