# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from likho.analytics.v1 import analytics_pb2 as likho_dot_analytics_dot_v1_dot_analytics__pb2


class AnalyticsServiceStub:
    """Owned by likho-analytics: the numbers behind the calls. It keeps every event of the platform
    in ClickHouse and answers what happened in a window - how many calls, how many minutes, how
    fast, in which languages, by whom, and what the model made of them.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOverview = channel.unary_unary(
                '/likho.analytics.v1.AnalyticsService/GetOverview',
                request_serializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetOverviewRequest.SerializeToString,
                response_deserializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetOverviewResponse.FromString,
                _registered_method=True)
        self.GetTimeseries = channel.unary_unary(
                '/likho.analytics.v1.AnalyticsService/GetTimeseries',
                request_serializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetTimeseriesRequest.SerializeToString,
                response_deserializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetTimeseriesResponse.FromString,
                _registered_method=True)
        self.GetBreakdown = channel.unary_unary(
                '/likho.analytics.v1.AnalyticsService/GetBreakdown',
                request_serializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetBreakdownRequest.SerializeToString,
                response_deserializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetBreakdownResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer:
    """Owned by likho-analytics: the numbers behind the calls. It keeps every event of the platform
    in ClickHouse and answers what happened in a window - how many calls, how many minutes, how
    fast, in which languages, by whom, and what the model made of them.
    """

    def GetOverview(self, request, context):
        """The window's totals: one card each on a dashboard.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimeseries(self, request, context):
        """One number per day (or hour) across the window: a chart.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBreakdown(self, request, context):
        """The window's calls split by agent, campaign, disposition, language or sentiment: a table.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOverview,
                    request_deserializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetOverviewRequest.FromString,
                    response_serializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetOverviewResponse.SerializeToString,
            ),
            'GetTimeseries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimeseries,
                    request_deserializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetTimeseriesRequest.FromString,
                    response_serializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetTimeseriesResponse.SerializeToString,
            ),
            'GetBreakdown': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBreakdown,
                    request_deserializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetBreakdownRequest.FromString,
                    response_serializer=likho_dot_analytics_dot_v1_dot_analytics__pb2.GetBreakdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likho.analytics.v1.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likho.analytics.v1.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService:
    """Owned by likho-analytics: the numbers behind the calls. It keeps every event of the platform
    in ClickHouse and answers what happened in a window - how many calls, how many minutes, how
    fast, in which languages, by whom, and what the model made of them.
    """

    @staticmethod
    def GetOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.analytics.v1.AnalyticsService/GetOverview',
            likho_dot_analytics_dot_v1_dot_analytics__pb2.GetOverviewRequest.SerializeToString,
            likho_dot_analytics_dot_v1_dot_analytics__pb2.GetOverviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimeseries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.analytics.v1.AnalyticsService/GetTimeseries',
            likho_dot_analytics_dot_v1_dot_analytics__pb2.GetTimeseriesRequest.SerializeToString,
            likho_dot_analytics_dot_v1_dot_analytics__pb2.GetTimeseriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBreakdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.analytics.v1.AnalyticsService/GetBreakdown',
            likho_dot_analytics_dot_v1_dot_analytics__pb2.GetBreakdownRequest.SerializeToString,
            likho_dot_analytics_dot_v1_dot_analytics__pb2.GetBreakdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
