# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from likho.transcription.v1 import transcription_pb2 as likho_dot_transcription_dot_v1_dot_transcription__pb2


class TranscriptionServiceStub:
    """Owned by likho-transcription: runs the speech model and stores both text layers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTranscript = channel.unary_unary(
                '/likho.transcription.v1.TranscriptionService/GetTranscript',
                request_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.GetTranscriptRequest.SerializeToString,
                response_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.GetTranscriptResponse.FromString,
                _registered_method=True)
        self.ListTranscripts = channel.unary_unary(
                '/likho.transcription.v1.TranscriptionService/ListTranscripts',
                request_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.ListTranscriptsRequest.SerializeToString,
                response_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.ListTranscriptsResponse.FromString,
                _registered_method=True)
        self.Transcribe = channel.unary_stream(
                '/likho.transcription.v1.TranscriptionService/Transcribe',
                request_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.TranscribeRequest.SerializeToString,
                response_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.TranscribeResponse.FromString,
                _registered_method=True)
        self.Retransliterate = channel.unary_unary(
                '/likho.transcription.v1.TranscriptionService/Retransliterate',
                request_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.RetransliterateRequest.SerializeToString,
                response_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.RetransliterateResponse.FromString,
                _registered_method=True)
        self.ListEngines = channel.unary_unary(
                '/likho.transcription.v1.TranscriptionService/ListEngines',
                request_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.ListEnginesRequest.SerializeToString,
                response_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.ListEnginesResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/likho.transcription.v1.TranscriptionService/CancelJob',
                request_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.CancelJobResponse.FromString,
                _registered_method=True)


class TranscriptionServiceServicer:
    """Owned by likho-transcription: runs the speech model and stores both text layers.
    """

    def GetTranscript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTranscripts(self, request, context):
        """All versions for one recording, newest first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transcribe(self, request, context):
        """Transcribes directly and streams lines as they are written (used by the CLI and tests;
        normal jobs arrive as likho.transcription.requested events).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Retransliterate(self, request, context):
        """Rebuilds the Hinglish layer from the saved script layer. The speech model does not run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListEngines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranscriptionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTranscript': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTranscript,
                    request_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.GetTranscriptRequest.FromString,
                    response_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.GetTranscriptResponse.SerializeToString,
            ),
            'ListTranscripts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTranscripts,
                    request_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.ListTranscriptsRequest.FromString,
                    response_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.ListTranscriptsResponse.SerializeToString,
            ),
            'Transcribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Transcribe,
                    request_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.TranscribeRequest.FromString,
                    response_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.TranscribeResponse.SerializeToString,
            ),
            'Retransliterate': grpc.unary_unary_rpc_method_handler(
                    servicer.Retransliterate,
                    request_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.RetransliterateRequest.FromString,
                    response_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.RetransliterateResponse.SerializeToString,
            ),
            'ListEngines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEngines,
                    request_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.ListEnginesRequest.FromString,
                    response_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.ListEnginesResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.CancelJobRequest.FromString,
                    response_serializer=likho_dot_transcription_dot_v1_dot_transcription__pb2.CancelJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'likho.transcription.v1.TranscriptionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('likho.transcription.v1.TranscriptionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranscriptionService:
    """Owned by likho-transcription: runs the speech model and stores both text layers.
    """

    @staticmethod
    def GetTranscript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.transcription.v1.TranscriptionService/GetTranscript',
            likho_dot_transcription_dot_v1_dot_transcription__pb2.GetTranscriptRequest.SerializeToString,
            likho_dot_transcription_dot_v1_dot_transcription__pb2.GetTranscriptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTranscripts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.transcription.v1.TranscriptionService/ListTranscripts',
            likho_dot_transcription_dot_v1_dot_transcription__pb2.ListTranscriptsRequest.SerializeToString,
            likho_dot_transcription_dot_v1_dot_transcription__pb2.ListTranscriptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transcribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/likho.transcription.v1.TranscriptionService/Transcribe',
            likho_dot_transcription_dot_v1_dot_transcription__pb2.TranscribeRequest.SerializeToString,
            likho_dot_transcription_dot_v1_dot_transcription__pb2.TranscribeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Retransliterate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.transcription.v1.TranscriptionService/Retransliterate',
            likho_dot_transcription_dot_v1_dot_transcription__pb2.RetransliterateRequest.SerializeToString,
            likho_dot_transcription_dot_v1_dot_transcription__pb2.RetransliterateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListEngines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.transcription.v1.TranscriptionService/ListEngines',
            likho_dot_transcription_dot_v1_dot_transcription__pb2.ListEnginesRequest.SerializeToString,
            likho_dot_transcription_dot_v1_dot_transcription__pb2.ListEnginesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/likho.transcription.v1.TranscriptionService/CancelJob',
            likho_dot_transcription_dot_v1_dot_transcription__pb2.CancelJobRequest.SerializeToString,
            likho_dot_transcription_dot_v1_dot_transcription__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
